"""Generate pure_stubs.h: no-op overrides for every pure virtual in CLO's Utility and
Pattern API interfaces, so the test hosts can instantiate fake APIs.

Generated from your local CLO SDK because the output is derived from CLO's headers,
which are not redistributed with this project.
"""
import os
import re
import sys

sdk = os.environ.get("CLO_SDK_DIR") or os.path.expanduser(
    r"~\clo_sdk_2025.2.236\CLO_SDK_v2025.2.236_WIN")
include = os.path.join(sdk, "CLOAPIInterface", "include")
out = ["// generated by gen_stubs.py from the local CLO SDK - do not commit", "#pragma once"]

for header, base, name in [("UtilityAPIInterface.h", "UtilityAPIInterface", "StubUtility"),
                           ("PatternAPIInterface.h", "PatternAPIInterface", "StubPattern")]:
    src = open(os.path.join(include, header), encoding="utf-8-sig").read()
    src = re.sub(r"//[^\n]*", "", src)
    decls = re.findall(r"virtual\s+([^;{}]*?\))\s*=\s*0\s*;", src, re.S)
    out.append("struct %s : CLOAPI::%s {" % (name, base))
    for d in decls:
        d = " ".join(d.split())
        out.append("\t" + d + (" override {}" if re.match(r"void\s", d) else " override { return {}; }"))
    out.append("};")

path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "pure_stubs.h")
open(path, "w", newline="\n").write("\n".join(out) + "\n")
print("wrote " + path)
sys.exit(0)
